config/objects/Artist__c.object
<CustomObject>
    <fields>
        <fullName>List_Cost__c</fullName>
        <label>List Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

config/objects/Performance__c.object
<CustomObject>
    <fields>
        <fullName>Artist__c</fullName>
        <label>Artist</label>
        <referenceTo>Artist__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking_Cost__c</fullName>
        <label>Booking Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performance</label>
    <nameField>
        <displayFormat>PERF-{0000}</displayFormat>
        <label>Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

config/objects/Show__c.object
<CustomObject>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PerformanceResultContainer.cls
public with sharing class PerformanceResultContainer
{
	
	public static String showId {get; set;}

	public boolean checked
	{
		get
		{
			if(checked == null)
			{
				if(performance.id <> null)
				{
					checked = true;
				}
				else
				{
					checked = false;
				}
				
			}
			return checked;
		}
		set;
	}

	public Performance__c performance
	{
		get
		{
			if(performance == null)
			{
				performance = new Performance__c(Show__c = showId, Artist__c = artist.id, Booking_Cost__c = artist.List_Cost__c);
			}
			if(performance.Booking_Cost__c == null)
			{
				performance.Booking_Cost__c = 0;
			}
			return performance;
			
		} 
		set;
	}
	public Artist__c artist {get; set;}

	public PerformanceResultContainer() {
		
	}


	public PerformanceResultContainer(Artist__c anArtist)
	{
		this();
		this.artist = anArtist;
	}
}