config/objects/Artist__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Draw__c</fullName>
        <label>Expected Draw</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Cost__c</fullName>
        <label>List Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alternative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rock</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

config/objects/Consumer__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Consumer</label>
    <nameField>
        <displayFormat>{0} - Member Since {YYYY}</displayFormat>
        <label>Consumer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

config/objects/Performance__c.object
<CustomObject>
    <fields>
        <fullName>Artist__c</fullName>
        <label>Artist</label>
        <referenceTo>Artist__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performance</label>
    <nameField>
        <displayFormat>PERF-{0000}</displayFormat>
        <label>Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

config/objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alternative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rock</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Shows</relationshipLabel>
        <relationshipName>Shows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestInit.cls
public class TestInit {
	// list of test artists
	public static List<Artist__c>artists
	{
		get
		{
			if(artists == null)
			{
				artists = new List<Artist__c>();
				artists.add(new Artist__c(name = 'Psy', Expected_Draw__c = '45654', List_Cost__c = 13548, Type__c = 'Pop'));
				artists.add(new Artist__c(name = 'Rihanna', Expected_Draw__c = '1371', List_Cost__c = 4574, Type__c = 'Pop'));
				artists.add(new Artist__c(name = 'Ke$ha', Expected_Draw__c = '4874', List_Cost__c = 45641, Type__c = 'Pop'));
				
				artists.add(new Artist__c(name = 'Linkin Park', Expected_Draw__c = '654312', List_Cost__c = 86741, Type__c = 'Rock'));
				artists.add(new Artist__c(name = 'Green Day', Expected_Draw__c = '65641', List_Cost__c = 85641, Type__c = 'Rock; Alternative'));
				artists.add(new Artist__c(name = 'The Killers', Expected_Draw__c = '45341', List_Cost__c = 65413, Type__c = 'Rock; Alternative'));
				
				artists.add(new Artist__c(name = 'Taylor Swift', Expected_Draw__c = '452324', List_Cost__c = 108023, Type__c = 'Country'));
				artists.add(new Artist__c(name = 'Jason Aldean', Expected_Draw__c = '7987', List_Cost__c = 72012, Type__c = 'Country'));
				artists.add(new Artist__c(name = 'Alan Jackson', Expected_Draw__c = '45667', List_Cost__c = 556874, Type__c = 'Country'));
				
				insert artists;
			}
			return artists;
		}
		set;
	}

	public static List<Show__c> shows
	{
		get
		{
			if(shows == null)
			{
				shows = new List<Show__c>();
				for(Venue__c v : venues)
				{
					shows.add(new Show__c(venue__c = v.id, Status__c = 'Proposed'));
					shows.add(new Show__c(venue__c = v.id, Status__c = 'On Sale'));
					shows.add(new Show__c(venue__c = v.id, Status__c = 'Sold out'));
					shows.add(new Show__c(venue__c = v.id, Status__c = 'Cancelled'));
					shows.add(new Show__c(venue__c = v.id, Status__c = 'Done'));
				}
				insert shows;
			}
			return shows;
		}
		set;
	}

	public static List<Performance__c> performances
	{
		get
		{
			if(performances == null)
			{
				performances = new List<Performance__c>();
				for(Show__c s : shows)
				{
					for(Artist__c a : artists)
					{
						performances.add(new Performance__c(Show__c = s.id, Artist__c = a.id));
					}
				}
				insert performances;
			}
			return performances;
		}
		set;
	}
	
	public static List<Consumer__c> customers
	{
		get
		{
			if(customers == null)
			{
				customers = new List<Consumer__c>();
				customers.add(new Consumer__c(First_Name__c = 'Arthur', Last_Name__c = 'Dent'));
				customers.add(new Consumer__c(First_Name__c = 'Ford', Last_Name__c = 'Prefect'));
				customers.add(new Consumer__c(First_Name__c = 'Zaphod', Last_Name__c = 'Beeblebrox'));
				insert customers;
			}
			return customers;
		}
		set;
	}
	
	public static List<Venue__c> venues
	{
		get
		{
			if(venues == null)
			{
				venues = new List<Venue__c>();
				venues.add(new Venue__c(Name = 'Bar Comida'));
				venues.add(new Venue__c(Name = 'Elbow Room'));
				venues.add(new Venue__c(Name = 'Pats Garage'));
				insert venues;
			}
			return venues;
		}
		set;
	}
}