config/objects/Artist__c.object
<CustomObject>
    <fields>
        <fullName>List_Cost__c</fullName>
        <label>List Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

config/objects/Performance__c.object
<CustomObject>
    <fields>
        <fullName>Artist_List_Cost__c</fullName>
        <formula>Artist__r.List_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>List cost of the Artist</inlineHelpText>
        <label>Artist List Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Artist__c</fullName>
        <label>Artist</label>
        <referenceTo>Artist__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking_Cost__c</fullName>
        <label>Booking Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Show__c</fullName>
        <label>Show</label>
        <referenceTo>Show__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performance</label>
    <nameField>
        <displayFormat>PERF-{0000}</displayFormat>
        <label>Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

config/objects/Show__c.object
<CustomObject>
    <fields>
        <fullName>Performer_Cost__c</fullName>
        <inlineHelpText>Total booking cost of the combined performances of the show</inlineHelpText>
        <label>Performer Cost</label>
        <summarizedField>Performance__c.Booking_Cost__c</summarizedField>
        <summaryForeignKey>Performance__c.Show__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Shows</relationshipLabel>
        <relationshipName>Shows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Show</label>
    <nameField>
        <label>Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_TriggerShowUpdateVenuesSumFields.cls
@isTest
public class Test_TriggerShowUpdateVenuesSumFields {
	

	private static testMethod void testVenueUpdateForInsertedPerformances()
	{
		List<Performance__c> performances = TestInit.performances;
		List<Artist__c> artists = TestInit.artists;


		AggregateResult sumOfStandardRatesOfArtists = [SELECT SUM(List_Cost__c) sumListCost FROM Artist__c];

		Map<Id, Double> sumPerVanue = new Map<Id, Double>();
		for(Show__c s : [SELECT Performer_Cost__c, Venue__c, Status__c FROM Show__c])
		{
			// Sum Performance Costs
			if(!sumPerVanue.containsKey(s.id))
			{
				sumPerVanue.put(s.id, 0);
			}
			if(s.Status__c == 'On Sale' && s.Status__c == 'Sold Out' && s.Status__c == 'Done')
			{
				sumPerVanue.put(s.id, sumPerVanue.get(s.id)+ s.Performer_Cost__c);
			}
			// Test Sum on Show level is correct
			System.assert(s.Performer_Cost__c == Double.valueOf(sumOfStandardRatesOfArtists.get('sumListCost')));
		}


		for(Venue__c v : [SELECT ID, Total_Show_Spend__c FROM Venue__c])
		{
			// System.assert(v.Total_Show_Spend__c == sumPerVanue.get(v.id));
		}


	}

	private static testMethod void testPerformanceChange()
	{
		testVenueUpdateForInsertedPerformances();
		List<Performance__c> performances = [SELECT ID, Booking_Cost__c, Artist_List_Cost__c FROM Performance__c];
		
		for(Integer i=0; i< performances.size(); i++)
		{
			if(Math.mod(i, 2) == 0)
			{
				performances.get(i).Booking_Cost__c = 42*Math.random();
			}
		}
		update performances;
	}

	private static testMethod void testPerformanceDelete()
	{
		testVenueUpdateForInsertedPerformances();
		List<Performance__c> performances = [SELECT ID, Booking_Cost__c, Artist_List_Cost__c FROM Performance__c];
		List<Performance__c> toBeDeleted = new List<Performance__c>();
		for(Integer i=0; i< performances.size(); i++)
		{
			if(Math.mod(i, 2) == 0)
			{
				toBeDeleted.add(performances.get(i));
			}
		}
		delete toBeDeleted;
	}

	private static testMethod void testShowDelete()
	{
		testPerformanceDelete();

		List<Show__c>toBeDeleted = new List<Show__c>();
		List<Show__c>shows = [SELECT ID FROM Show__c];

		for(Integer i = 0; i<shows.size(); i++)
		{
			if(Math.mod(i, 2) == 0)
			{
				toBeDeleted.add(shows.get(i));
			}
		}

		delete toBeDeleted;
	}
}