config/objects/Artist__c.object
<CustomObject>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

config/objects/Performance__c.object
<CustomObject>
    <fields>
        <fullName>Artist__c</fullName>
        <label>Artist</label>
        <referenceTo>Artist__c</referenceTo>
        <relationshipLabel>Performances</relationshipLabel>
        <relationshipName>Performances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performance</label>
    <nameField>
        <displayFormat>PERF-{0000}</displayFormat>
        <label>Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_TestInit.cls
@isTest
private class Test_TestInit
{
	// Test vanues
	private static testMethod void test_Insert_Venues()
	{
		System.assert(TestInit.venues.size() == [SELECT ID FROM Venue__c].size(), 'Not all venues were inserted');
	}

	// Test artists
	private static testMethod void test_Insert_Artists()
	{
		System.assert(TestInit.artists.size() == [SELECT ID FROM Artist__c].size(), 'Not all artists were inserted');
	}
	// Test performances
	private static testMethod void test_Insert_Performances()
	{
		List<Performance__c> performances = TestInit.performances;
		System.assert(TestInit.venues.size()*TestInit.artists.size()*5 == [SELECT ID FROM Performance__c].size());
	}
}